feat(server): add ELF signing using delivery-kit-sdk
Signed-off-by: Dmitry Mordvinov <dmitry.mordvinov@flant.com>

diff --git a/server/Taskfile.yaml b/server/Taskfile.yaml
--- a/server/Taskfile.yaml
+++ b/server/Taskfile.yaml
@@ -9,6 +9,7 @@ includes:
     vars:
       paths: ". cmd/** pkg/**"
       golangciLintBinDir: "../bin"
+      golangciLintVersion: "v1.64.2"
 vars:
   project_name: '{{.project_name | default "trdl-test-project1"}}'
   signatures_count: '{{.signatures_count | default "0"}}'
@@ -20,6 +21,7 @@ vars:
   minio_data_dir: '{{.minio_data_dir | default ".minio_data"}}'
   minio_container: '{{.minio_container | default "trdl_dev_minio"}}'
   vault_container: '{{.vault_container | default "trdl_dev_vault"}}'
+  vault_dev_image: '{{.vault_dev_image | default "ghcr.io/werf/trdl-dev-vault:latest"}}'
   s3_access_key: '{{.s3_access_key | default "minioadmin"}}'
   s3_secret_key: '{{.s3_secret_key | default "minioadmin"}}'
   minio_port: '{{.minio_port | default "9000"}}'
@@ -28,6 +30,8 @@ vars:
   version: '{{.version | default "dev"}}'
   vault_version: "1.20.4"
   plugin_dir: "./vault/plugins/"
+  cgoTags: "osusergo netgo static_build"
+  cgoLDFlags: "-extldflags=-static"
 
 tasks:
   restart:
@@ -68,7 +72,7 @@ tasks:
       - |
         docker run --workdir /app --privileged --name {{.vault_container}} -e VAULT_PLUGIN_SECRETS_TRDL_PPROF_ENABLE=1 \
         -e VAULT_PLUGIN_SECRETS_TRDL_DEBUG=1 --detach --volume /var/run/docker.sock:/var/run/docker.sock \
-        --volume ./:/app -p {{.vault_port}}:{{.vault_port}} ghcr.io/werf/trdl-dev-vault:latest server -dev \
+        --volume ./:/app -p {{.vault_port}}:{{.vault_port}} {{.vault_dev_image}} server -dev \
         -dev-root-token-id=root -dev-plugin-dir=/app/vault/plugins -log-level trace
       - |
         while ! docker exec {{.vault_container}} vault status; do
@@ -175,6 +179,41 @@ tasks:
           raceDetectorEnabled: '{{.raceDetectorEnabled | default "false"}}'
           outputDir: vault/plugins
 
+  deps:install:c:
+    desc: "Install C dependencies required by delivery-kit-sdk ELF signing."
+    cmds:
+      - |
+        set -eux
+
+        ARCH=$(uname -m)
+        case $ARCH in
+          "x86_64")
+            ARCH="amd64"
+            ;;
+          *)
+            echo "Unsupported architecture: $ARCH"
+            exit 1
+            ;;
+        esac
+
+        SUDO=""
+          if [ "$(id -u)" -ne 0 ]; then
+            if command -v sudo >/dev/null 2>&1; then
+              SUDO="sudo -E -n"
+            fi
+        fi
+
+        if command -v apt-get >/dev/null 2>&1; then
+          export DEBIAN_FRONTEND=noninteractive
+          $SUDO apt-get -y update
+          $SUDO apt-get install -y libuv1-dev libzstd-dev zlib1g-dev libssl-dev libelf-dev
+
+          $SUDO ln -fs "$(dpkg -L libuv1-dev | grep -F '/libuv_a.a')" /usr/lib/x86_64-linux-gnu/libuv.a
+        else
+          echo "Can't install C dependencies automatically, do it manually."
+          exit 1
+        fi
+
   build:all:
     desc: "Build all server binaries."
     deps:
@@ -202,6 +241,7 @@ tasks:
         vars:
           targetOS: "linux"
           targetArch: "amd64"
+          cgoEnabled: "1"
           outputDir: vault/plugins
 
   build:dev:linux:arm64:
@@ -220,7 +260,8 @@ tasks:
         vars:
           targetOS: "linux"
           targetArch: "amd64"
-          extraGoBuildArgs: -ldflags="-s -w"
+          cgoEnabled: "1"
+          stripDebug: "true"
           outputDir: "dist/{{.version}}/linux-amd64/bin/"
 
   build:dist:linux:arm64:
@@ -230,7 +271,7 @@ tasks:
         vars:
           targetOS: "linux"
           targetArch: "arm64"
-          extraGoBuildArgs: -ldflags="-s -w"
+          stripDebug: "true"
           outputDir: "dist/{{.version}}/linux-arm64/bin/"
 
   _build:go:
@@ -238,11 +279,13 @@ tasks:
     cmds:
       - |
         go build -o {{.outputDir | default (printf "vault/plugins/%s/%s-%s/bin" .version .targetOS .targetArch)}}/vault-plugin-secrets-trdl{{if (eq .targetOS "windows")}}.exe{{end}} \
+        {{if eq (.cgoEnabled | default "0") "1"}}-tags="{{.cgoTags}}" -ldflags="{{.cgoLDFlags}}{{if eq (.stripDebug | default "false") "true"}} -s -w{{end}}"{{else if eq (.stripDebug | default "false") "true"}}-ldflags="-s -w"{{end}} \
         {{.extraGoBuildArgs}} {{.CLI_ARGS}} github.com/werf/trdl/server/cmd/vault-plugin-secrets-trdl
     env:
       GOOS: "{{.targetOS}}"
       GOARCH: "{{.targetArch}}"
-      CGO_ENABLED: 0
+      CGO_ENABLED: '{{.cgoEnabled | default "0"}}'
+      CC: '{{.cc | default "gcc"}}'
 
   build-with-coverage:
     desc: "Build server binary to run E2E tests with coverage."
